### ISSUE TITLE
Driver request for rt3573

### ISSUE THREAD

**Issue by Darkknight33** [OpenELEC/OpenELEC.tv#1182]
Seems raylink has a compatible Linux driver, but it hasn't yet gotten integration in to the kernel. Can you please add the needed driver?

http://www.wikidevi.com/wiki/TRENDnet_TEW-684UB

**Comment by olf-folks** [comment]
looks like i make 4 people that want this, i have a more up to date kernel and it still dose not work. i don't remember any non opensource bits about this driver before when i compiled it for kali-linux. and the reason there are only 4 peephole that want this is because not everyone wants to make an account here just to post this. because it would be more fast/easy to just install something better that has support for the  ralink rt3573.

**Comment by olf-folks** [comment]
5 https://github.com/OpenELEC/OpenELEC.tv/issues/2748
