### ISSUE TITLE
Raspberry PI: Check STORAGE before mount

### ISSUE THREAD

**Issue by 1358** [OpenELEC/OpenELEC.tv#2050]
As the RPi has no power management features build in, it happens from time to time that it is powered off, when the SD card is still in use.

Other Linux distributions handle this by checking each volume automatically during boot right before mountig if it is in an inconsistent sate, or even provide policies to force a check during every boot. (touch /forcefsck, tune2fs -c, and so on)

I know that this can take some time on the RPi, however waiting even a few minutes is better than data loss and the need of another linux machine, to run fsck -fy /dev/mmcblk0p2.

**Comment by redraw** [comment]
Is this fixed? This is the message:
```
***Error in check_disks:could not repair filesystem, dropping to debug shell, try to run 'fsck' manually:***
### Starting debugging shell... Type exit to quit ###
Sh: can't access tty; job control turned off
```
So, by manually running:
```
# fsck -fy /dev/mmcblk0p2 
# reboot
```
it should be repaired. However, I haven't got SSH access to do that, @1358 
I have no access to the Raspberry, and I need to send a person to do that. This is painful.
Is there any workaround?

**Comment by MilhouseVH** [comment]
> it should be repaired.

Actually, there's no guarantee the file system can be repaired manually, otherwise repair would have happened automatically, but since it failed you're now in this rather terminal situation.

>  @sraue Is there any workaround?

Not if you can't access the device remotely. Sending someone or physical recover is your only option. If this is a costly exercise, then investing more money in the hardware may be prudent, although the source of filesystem corruption (assuming this is a Pi2) is in the process of being identified (https://github.com/raspberrypi/firmware/issues/397)
