### ISSUE TITLE
sh: rsync: not found

### ISSUE THREAD

**Issue by ysim** [OpenELEC/OpenELEC.tv#2539]
I'm using OpenELEC version 3.0.6. I got this message when attempting to rsync something; I was prompted for the password, but after that...

``` bash
sh: rsync: not found
rsync: connection unexpectedly closed (0 bytes received so far) [sender]
rsync error: remote command not found (code 127) at /SourceCache/rsync/rsync-40/rsync/io.c(452) [sender=2.6.9]
```

With a `127` error code. 

I found a workaround in the old issue tracker here: https://code.google.com/p/openelec/issues/detail?id=9

But it would be nice to have rsync "just work" rather than have to specify that path every time I run the command.

**Comment by jpluimers** [comment]
Since the old repository on Google code is archived now, it is good to know most it is on the Wayback Machine including the [referred issue](https://web.archive.org/web/20141105043941/http://code.google.com/p/openelec/issues/detail?id=9). From there:

Workaround 1:

> workaround/solution:
> connect to openelec, see what is path to `rsync` command i.e.
> 
> ``` text
> openelec:~ # which rsync
> /storage/.xbmc/addons/network.backup.rsync/bin/rsync
> ```
> 
> and add that path to rsync command on remote computer i.e.
> 
> ``` text
> rsync --rsync-path=/storage/.xbmc/addons/network.backup.rsync/bin/rsync ... 
> ```

Workaround 2:

> Thanks, I ended up doing something similar:
> 
> ``` text
> rsync --rsync-path='. /etc/profile; rsync' ...
> ```
>
> This works at least on OpenELEC 4 as `/etc/profile` parses the add-ons directories to add the programs add-ons to the path. It is essentially your workaround just a little easier to type.

I prefer the second workaround as both `/etc/profile` is easier to remember than path to `rsync`, and `/etc/profile` might initialise other dependencies needed during the `rsync` operation.
