### ISSUE TITLE
Xbox 360 wireless controller not working anymore (since OE 3.2)

### ISSUE THREAD

**Issue by bhabba** [OpenELEC/OpenELEC.tv#2607]
Since I've upgraded from Openelec (ION x64 build) version 3.0.6 to 3.2 my Xbox 360 wireless controller doesn't work anymore. This is obviously a regression because there was a similar issue in the past which had been fixed in version 3.0 RC3 (see https://github.com/OpenELEC/OpenELEC.tv/issues/1580).

The controller is connected through the common USB receiver (third party replica of the official microsoft one): http://support.xbox.com/en-US/xbox-360/accessories/xbox-360-wireless-gaming-receiver-windows

**Comment by musyne** [comment]
Hi,

It's still not working on a Raspberry Pi B+.
I have tried both 5.0 official and the build from @zzattack.
However, I tried 5.0 official on a x86 (NUC DN2820FYKH) and it works fine (although the lights keep blinking) so I guess the bug is specific to the ARM build.
Anything I can do to help investigate the issue?

**Comment by bonds** [comment]
Awesome @zzattack, thanks for working on this! I'm excited about this ticket. :)

**Comment by yene** [comment]
Hi,
I can confirm Xbox 360 controller does not work on Raspberry Pi 2 Model B. I also have wireless xbox 360 controller and a xbox one controller if you want me to do some testing.

**Comment by jbreitbart** [comment]
I have a wireless and a wired XBox 360 controller on for my Pi2. If there is anything to test I would like to help!

**Comment by lrusak** [comment]
@yene @jbreitbart No joystick support in Kodi on the RPi. Please search
