### ISSUE TITLE
Add settings for proper working deinterlace on i.MX6

### ISSUE THREAD

**Issue by piotrasd** [OpenELEC/OpenELEC.tv#3919]
Hi
i saw some changes for deinterlace for i.mx6 but i dont saw this

"Recommendations for client setup:
enable VPU@352Mhz in kernel
setup 32 bit framebuffer in uEnv.txt (bpp=32)
disable console blanking in uEnv.txt (consoleblank=0)"

please also look here
"https://github.com/xbmc/xbmc/pull/6351"

**Comment by fritsch** [comment]
Grrr, Do that again and I will personally ban you from this github.

You don't have a single clue on what we have in OpenELEC and what not ...
Everything is in there - besides that forced overclock - you can do that personally for your hardware, if you are not afraid to kill it. OE will never operate hw out of spec and overclock if not clearly stated otherwise by the vendor.
