### ISSUE TITLE
Option to have vpn autostart

### ISSUE THREAD

**Issue by micaca** [OpenELEC/OpenELEC.tv#4007]
hello is that possible to have an option in vpn configuration to make my connexion autostart ?
Thank you

**Comment by micaca** [comment]
why my request is invalid ?

**Comment by chewitt** [comment]
It's invalid because a) you have ignored the clearly documented protocol for development contributions to the project, and b) because we removed the OE provided GUI for VPN (which has been visible in the master branch of the project for months already) and c) because you can do this from an autostart.sh script which takes 1-2 minutes to write. There are already threads on this kind of thing in the forums, which is a more appropriate place to have a discussion - this is NOT a help channel.
