### ISSUE TITLE
OE6 gbd0c825 nvidia 352.21 : Switch to 50Hz fails on GT520M

### ISSUE THREAD

**Issue by ozolli** [OpenELEC/OpenELEC.tv#4204]
Hi devs,

With the nvidia driver 352.21 with a 25Hz video Kodi fails to switch to 50Hz and "fallbacks" to 23.976Hz (default freq  that I set on my Xtreamer Ultra2).

Switch to any other freq is ok.

Kodi log : http://sprunge.us/SSRG
Xorg log : http://sprunge.us/CCId
xorg.conf : http://sprunge.us/UeNS

No problem with the same git version and nvidia 349.16

**Comment by stefansaraev** [comment]
thanks for reporting this. but we can not fix it. pls also report to nvidia ;)

**Comment by ozolli** [comment]
Thanks for your answer Stefan.
Shall I point nvidia to the same logs? Will they be of any help for them?
Seems the 352 series is a bit young as for now ;)

**Comment by chewitt** [comment]
I am using an Ultra2 and play a lot of 25Hz BBC iPlayer content which is played at 50Hz with no issues using any OE version since "2.0" days. The xorg.conf you are using looks to be derived from one that I posted some time back (the clue is the 23.976 modeline which is tuned to extra decimal places) but you are missing other xorg.conf elements which are normally important. I would remove it and retest with the current beta. I am closing the ticket - for further help/support please start a forum thread.
