### ISSUE TITLE
[5.95.x] CEC on WetekPlay does not work. It did in 5.x versions

### ISSUE THREAD

**Issue by walterheisenberg** [OpenELEC/OpenELEC.tv#4305]
The CEC on every 5.95.x version of OE is not working. And it is not only me, many ppl reported, that CEC on the WetekPlay does not work with 5.95.x. It worked with the 5.x versions.

examples:
http://wetekforums.com/vb5/forum/wetek-play/linux/openelec/15492-openelec-5-95-5-released-for-wetek-play?p=15624#post15624
http://wetekforums.com/vb5/forum/wetek-play/linux/openelec/15290-cec-function-stopped-working-after-upgrade-to-5-95-4-nand (with dmesg-log)
http://openelec.tv/forum/148-usage/76782-cec-toshiba-regza-remote-not-working-with-6-x
http://openelec.tv/forum/146-wetek-play/77018-cec-support#141674 and below (#11 and #12)
```
echo 0x0f > /sys/class/amhdmitx/amhdmitx0/cec_config
```
or
```
echo 1 > /sys/devices/virtual/amhdmitx/amhdmitx0/cec_config
```
didn't work. Enabling CEC on Android before did also not help.

It worked in 5.x, so please make it work in 6.x versions also
Thx

**Comment by qods** [comment]
You can try out 3.0.1 with this patch here:
https://github.com/OpenELEC/OpenELEC.tv/pull/4362

OpenELEC would bump to anything newer then 3.0.1 when its released to hopefully fix this bug. Until then it would be helpefull if you report if the listed patch fix your problem.

**Comment by stefansaraev** [comment]
@qods you have no idea what you are talking about. please stop now!. wetek is not using libcec.

@walterheisenberg an official OE 5.0.x was never released for wetek play. so, honestly, most of us have no clue "how" it worked before ;)

cc @codesnake

**Comment by codesnake** [comment]
@stefansaraev is right WeTek doesn't use libcec, because libcec doesn't support Amlogic SoCs.
In unofficial 5.0.x builds we had Amlogic CEC implementation enabled by default, but currently we disabled because it is unstable.
However `echo 0x0f > /sys/class/amhdmitx/amhdmitx0/cec_config` should work in most cases. At least it works on my LG TV, but may suddenly stop working.

**Comment by qods** [comment]
@stefansaraev 
Thanks for the information. Because noone have answered to this bugreport for a month i tried helping.

**Comment by kdietrich** [comment]
@codesnake Many people are reporting that they had fully working CEC in 5.0.8. Me too. I'm using a Samsung TV and since 5.1.0 CEC is not working anymore even when I'm using your command to explicitly enable it. So the default deactivation can't be the only thing that has changed from 5.0.8 to 5.1.0.

see e.g. http://wetekforums.com/vb5/forum/wetek-play/linux/openelec/17514-hdmi-cec-with-samsung-tv?p=17643#post17643

Anyway: What are the chances to get a libcec build for Amlogic? I've read that more and more Android HTPC are supported recently. CEC is imho the only thing where the raspberry has the edge over the wetek.

**Comment by jester-xbmc** [comment]
just my 2 cents:

as you are selling the box quoting cec support, enable cec by default, it might be unstable for now but at least its working for some people (many samsung people reporting it working after the manual comand etc.) and its saves you from doing manual commands and there doesn't seem to be any impact in enabling it.

Current workaround on my new wetek openelec test box running beta 5.95.5 on samsung tv:
create /storage/.config/autostart.sh
insert: echo 0x0f > /sys/class/amhdmitx/amhdmitx0/cec_config
reboot

**Comment by chewitt** [comment]
@codesnake - what's the latest on your efforts to restore a "stable" CEC capability to WP?

**Comment by codesnake** [comment]
Currently the best way to enable HDMI CEC on WeTek Play and OE box is to use this addon: http://openelec.tv/forum/146-wetek-play/78681-wetek-hdmi-cec-enabler-add-on

**Comment by sraue** [comment]
should work in 6.0.3 and master
