### ISSUE TITLE
Kodi 15.2 Final Release

### ISSUE THREAD

**Issue by lrusak** [OpenELEC/OpenELEC.tv#4350]
Waiting for Kodi 15.2 Final

**Comment by odc2** [comment]
There are also many other bugs on 6.0.0 that should be fixed before releasing 6.0.0

**Comment by fritsch** [comment]
Thank you very much for spamming github. I cannot see a single proper bugreport opened by you @odc2 with relevant logfiles.

**Comment by odc2** [comment]
@fritsch 
I have reported here a bug with logfiles (debugging enabled):
https://github.com/OpenELEC/OpenELEC.tv/issues/4351
You write that you cant see a single bugreport with relevant logfiles. I dont know what logfiles i should report. I reported the kodi logfiles with debugging enabled. Isnt that "relevant"? If there are more files needed, just tell me what i should provide.

And i talk also for example about the CEC errors that have been reported multiple times. I dont have CEC supported device but there seems to be something wrong because so many people are reporting bugs about this.

**Comment by fritsch** [comment]
You make a big fault: Something does not work for personally you and you think it does not work for everyone ... which is just completely wrong.

**Comment by fritsch** [comment]
But - you got luck today. I need to travel tonight and will take my never opened OpenELEC box with me ... there I will install 5.95.5 to NAND and will try to get VDR + vnsi running.

I will report back later tonight or tomorrow morning.

**Comment by anoma** [comment]
https://github.com/xbmc/xbmc/pull/8249

**Comment by sraue** [comment]
added in https://github.com/OpenELEC/OpenELEC.tv/commit/1bdbcac4a57722895260ba4e8ce4447cf41c57d5
