### ISSUE TITLE
Raspberry Pi ntpd not started

### ISSUE THREAD

**Issue by trevorjharris** [OpenELEC/OpenELEC.tv#4586]
Have Raspberry pi 2 running Kodi 17.0 release 106

The raspberry pi does not have a real time clock and so relies on ntp for setting the time. Setting the timeservers in Kodi has no effect because ntpd is not started. I got round the by adding "/sbin/ntpd -p pool.ntp.org" to autostart.sh. Please could the code be changed to start ntpd if a timeserver is set.

**Comment by lrusak** [comment]
If you set the timezone in Kodi (system --> appearance --> international) the time will be set.

see, https://github.com/OpenELEC/OpenELEC.tv/blob/master/packages/mediacenter/kodi/patches/kodi-100.08-setup-timezone.patch

**Comment by chewitt** [comment]
The issue is that connman automatically attempts ntp sync using its own methods after it is started (using pool.ntp.org servers defined in /etc/connman/main.conf) but as the network is not fully up (usually due to slow loading wifi drivers, but sometimes other things) the initial attempt fails. connman will re-attempt sync automatically but it can be a minute or two later. The autostart.sh script is just forcing sync after the initial failure and before the next automatic one.

@lrusak @sraue - this is probably a test case for the connman-wait-online function added in connman 1.31 - which I think (as I didn't look at the code yet) delays various internal connman things like ntp sync until the network is confirmed to be fully up.

**Comment by chewitt** [comment]
@trevorjharris - please test a current milhouse build containing "connman-wait-online" changes to see if this issue has been resolved? - Thanks.
