### ISSUE TITLE
openELEC 6 on RPi2 can't play some MPEG4 with resolution 720x756

### ISSUE THREAD

**Issue by iivailo** [OpenELEC/OpenELEC.tv#4587]
Some channels with MPEG4 and resolution 720x576 aren't watchable on RPi 2 with openELEC 6. The problem doesn't exist on x86 PC with AMD GPU and Wetek Play. HD channels are OK on RPi2 only SD channels are affected. I have created 10min  sample. The sample is watchable on Wetek Play and x86 PC(both are using openELEC 6), but not on RPi 2. Here is a link to the sample: https://copy.com/RGzqNKN3OCv7otDo

I also tried OpenELEC-RPi2.arm-6.0-Milhouse-20150701210203-#0701-g96e5cfe, but the problem hasn't been fixed.

**Comment by InuSasha** [comment]
maybe the file is corrupt? VLC can't play it, too via hardware decoder.
[00007f9f14c0d618] avcodec decoder: Using NVIDIA VDPAU Driver Shared Library  340.93  Wed Aug 19 16:27:32 PDT 2015 for hardware decoding.
[h264 @ 0x7f9f14ccbc20] reference picture missing during reorder
[h264 @ 0x7f9f14ccbc20] reference picture missing during reorder
[h264 @ 0x7f9f14ccbc20] Missing reference picture
[h264 @ 0x7f9f14ccbc20] Missing reference picture
[h264 @ 0x7f9f14d28c20] reference picture missing during reorder
[h264 @ 0x7f9f14d28c20] reference picture missing during reorder
[h264 @ 0x7f9f14d28c20] Missing reference picture
[h264 @ 0x7f9f14d28c20] Missing reference picture

**Comment by iivailo** [comment]
Wetek Play with OE6 plays the sample without artefacts and I expect the same behaviour on RPi 2.

**Comment by MilhouseVH** [comment]
Latest RPi2 test build (Kodi 17, #0107) plays the sample but is unmatchable due to artefacts.

VLC on Windows plays the sample OK, apart from artefacts at initial start of play.

I'd suggest posting the sample to the [OpenELEC Test Build](http://forum.kodi.tv/showthread.php?tid=250817) thread where @popcornmix can give his opinion.

**Comment by popcornmix** [comment]
This is an example of https://github.com/raspberrypi/firmware/issues/499
We've aware of the issue and it is high priority so I hope we'll have a solution soon.

**Comment by apexo** [comment]
This seems to have been fixed in raspberrypi/firmware as of Jan 13th: https://github.com/raspberrypi/firmware/commit/98dca219c7955a189a5114c3144d416645388f15

However, OpenELEC 6.0.1 (released on Jan 30th) doesn't seem to include that fix.

It would be great if there was a list of the versions/git revisions of the different components that are used in OpenELEC.

**Comment by sraue** [comment]
this list is here: https://github.com/OpenELEC/OpenELEC.tv/commits/openelec-6.0 for the rpi firmware https://github.com/OpenELEC/OpenELEC.tv/commits/openelec-6.0/packages/graphics/bcm2835-driver and https://github.com/OpenELEC/OpenELEC.tv/commits/openelec-6.0/packages/tools/bcm2835-bootloader

**Comment by apexo** [comment]
Sorry, missed that.

Please update packages/graphics/bcm2835-driver to at least rev 98dca21 (or the latest rev: 565197e). That should fix this issue.

**Comment by apexo** [comment]
Apparently this is now fixed in master https://github.com/OpenELEC/OpenELEC.tv/commit/08da0d4e8b2161483218f5d1318a7e141013e2df but has not made it to 6.0.3.

**Comment by sraue** [comment]
updated in https://github.com/OpenELEC/OpenELEC.tv/commit/fcc416b2845de2c686a9207859926326bee654e9
