### ISSUE TITLE
Generic x64 6.95.2 Openelec doesn't start after installing a hdd

### ISSUE THREAD

**Issue by stromrickard** [OpenELEC/OpenELEC.tv#4932]
After installing a hard drive in my HTPC, Openelec stops with an error:
*** Error in mount_flash: mount_common: Could not mount /dev/sda2 ***
### Starting debugging shell... type exit to quit ###
sh: can't access tty; job control turned off

This happens on a Zotac AD10. I've been using Openelec booting from an SD-card without any hdd.
What i did was to remove the SD-card, installed a HDD, installed Windows 10 on it, added the SD-card again and set UEFI to boot from the SD again.
If i either remove the HDD or disable the SATA-controller in UEFI, Openelec starts fine.

I know logs are needed but not sure how to provide them in this case.

**Comment by stefansaraev** [comment]
logs are not needed.

this seems to be (unsupported) manual installation. but you should at least use UUIDs or LABELs in /flash/syslinux.txt, instead of /dev/sda*

boot a linux rescue cd / stick, do: blkid, copy the UUIDs for /flash and /storage partition and then change syslinux.txt accordingly: boot=UUID=uuid-of-sda1 disk=UUID=uuid-of-sda2

this way your OE installation will be "portable". btw OE has a forum for support questions. this is adevelopment  bug tracker.

**Comment by stromrickard** [comment]
Thanks!

Indeed, i followed the guide for dualboot with Ubuntu. Sorry for posting in wrong place.
